name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: config Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: install dependencies
      run: cd myfrontend && npm install

    - name: run linter
      run: cd myfrontend && npm run lint

    - name: execute tests
      run: cd myfrontend && npm run test

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -f ./Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/parabolic-game:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/parabolic-game:latest

